version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    networks:
      - transactions-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka_broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # To create topics when referenced by producer or consumer
    ports:
      - 9092:9092
    networks:
      - transactions-network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: salima
      DOCKER_INFLUXDB_INIT_PASSWORD: 123*/salima*/@*/
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: TP-fraud-detection
      DOCKER_INFLUXDB_INIT_RETENTION: 1d
    ports:
      - 8086:8086
    networks:
      - transactions-network
    volumes:
      - ./influxdb:/var/lib/influxdb2

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    networks:
      - transactions-network
    volumes:
      - ./grafana:/var/lib/grafana

volumes:
  influxdb:
  grafana:

networks:
  transactions-network: